### ISSUE TITLE
Extension Path in the variables Array to address files and folders correctly the css

### ISSUE THREAD

**Issue by Mumpitz** [svewap/ws_scss#1]
I can only pass plain strings to the variables array in the TypoScript.

To be able to link fonts and images correctly that are, for example embedded in an Extension, it would be nice to be able to write something like
```typoscript
plugin.tx_wsscss.variables {
	fontPath = path:EXT:myext/Resources/Public/Fonts/
}
```
and then use it for `@font-face` definitions.

Then i am able to use my extension also as a global extension or change my folder structure and nothing will break.

Maybe it is possible to add the same parser that is used for TEXT cObjects?

**Comment by svewap** [comment]
This is not possible at this moment for directories, because the ContentObjectRenderer class does not support this. This is only possible for files.
Workaorund:
```
plugin.tx_wsscss.variables {
  font-path = TEXT
  font-path.data = path:EXT:template/Resources/Public/Fonts/.dir
  font-path.stdWrap.substring = 0,-4
}
```
