### ISSUE TITLE
PostCSS Support

### ISSUE THREAD

**Issue by ArminVieweg** [svewap/ws_scss#11]
Hey,
first thank you very much for this awesome extension! I've tried it first time, few weeks ago (in TYPO3 9.5) and it works like charm! 👍 

I think about replacing our current NPM/Gulp/Whatever-Stack, which we use currently to build CSS out of SASS. But for TYPO3 projects only, this is a pretty huge overhead.

I asked my Frontend developers and they say, that we also use a tool called PostCSS, which goes through the rendered CSS and add vendor-prefixes to increase the compatibility for crappy browsers (like IE 10).

Is there a possibility to apply PostCSS here as well? I've checked packagist for PHP PostCSS tools, but the most recent one I've found is two years old and "unofficial".

Maybe there is no alternative for PostCSS existing in PHP... but I wanted to ask you first, before surrendering. 

Thanks!
Armin

**Comment by svewap** [comment]
Hi Armin!
I didn't found a postcss in PHP too. That's why I'm using csscrush. That does the same. CssCrush is call by the Autoprefixer class.

```
main = EXT:template/Resources/Private/SCSS/bootstrap.scss
main.outputfile = typo3temp/assets/css/main
main.formatter = WapplerSystems\WsScss\Formatter\Autoprefixer
```
Does this help?

**Comment by ArminVieweg** [comment]
Very cool! Thank you. I'll try it :)

**Comment by ArminVieweg** [comment]
It works like charm. Thank you very much! 👍

**Comment by svewap** [comment]
You're welcome!

**Comment by bh-teufels** [comment]
In Version 1.2 

https://docs.typo3.org/p/svewap/ws-scss/1.2/en-us/Usage/Index.html#formatter
Formatters are deprecated by the scssphp compiler and not supported anymore.

is there a Solution for Version 1.2 of svewap/ws_scss ?
