### ISSUE TITLE
bootstrap 4.2 compile error

### ISSUE THREAD

**Issue by maxisuess** [svewap/ws_scss#13]
When i want to compile the source scss files of bootstrap 4.2 i get this error:
parse error: failed at `&} {`<mydomain>/bootstrap/mixins/_badge.scss on line 5

**Comment by BastianBalthasarBux** [comment]
Hmm, same on boostrap v 4.3.1.
But it seems, that is a scssphp issue:
https://github.com/leafo/scssphp/issues/614 and
https://github.com/leafo/scssphp/issues/616

**Comment by svewap** [comment]
This problem was fixed.
