### ISSUE TITLE
Deprecation Warning with TYPO3 v9.0

### ISSUE THREAD

**Issue by andreashager** [svewap/ws_scss#14]
Hallo,

When I run ws_scss with TYPO3 v9.0 I get the following deprecation warning:
`Deprecated: TemplateService->getFileName() will be removed in TYPO3 v10.0. Use FilePathSanitizer->sanitize() of EXT:frontend instead. in .../typo3/sysext/core/Classes/TypoScript/TemplateService.php on line 1439`

Best regards,
Andi 😃

**Comment by svewap** [comment]
Fixed in next release
