### ISSUE TITLE
PHP Error after update to version 1.1.13 - breaks website

### ISSUE THREAD

**Issue by Teisi** [svewap/ws_scss#16]
500 Error at TYPO3 frontend and backend

TYPO3 8.7.27
PHP 7.0.33-0ubuntu0.16.04.4

PHP Parse error:  syntax error, unexpected '=' in .../typo3conf/ext/ws_scss/Classes/Hooks/RenderPreProcessorHook.php on line 144, referer: https://domain.tld

**Comment by svewap** [comment]
You are using too low a PHP version. As a minimum, 7.1 is specified in the dependencies.

**Comment by Teisi** [comment]
hmm ok 
I overlooked that, but then the dependency in the ext_emconf.php "'php' => '7.1.0-7.3.99'," is wrong, because there are only TYPO3 extensions allowed:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/DeclarationFile/Index.html

PHP Version check is not implemented in TYPO3 extensionmanager.

**Comment by svewap** [comment]
Why is it wrong? There is an example for a php dependency on this site.
Maybe this is a missing feature.
PHP 7.0 isn't supported anymore. You can run TYPO3 8 with higher version 7.1 or 7.2 . Shouldn't be a problem.

**Comment by Teisi** [comment]
hmm you are right there is an example -- but the sentence sad:
"depends
List of extensions that this extension depends on. Extensions defined here will be loaded before the current extension."

So only extensions are checked.
-----------------

I tested this with the string "PHP" locally.
Locally TYPO3 actually tests the PHP version.
Hmm on the server not. 
Ok excuse me(!) then this is probably a bug of TYPO3 I write this in forge.
Thanks for your time :)
-----------------

Question answere ("PHP 7.0 isn't supported anymore."):
in my case i have unfortunately no control over the PHP-version...

**Comment by svewap** [comment]
> Question answere ("PHP 7.0 isn't supported anymore."):
> in my case i have unfortunately no control over the PHP-version...

Oh oh :-(  . Please inform your customer that there are no security fixes for this version anymore. https://www.php.net/supported-versions.php
