### ISSUE TITLE
Undefinded variable $colors / bootstrap

### ISSUE THREAD

**Issue by seitenformate** [svewap/ws_scss#18]
Hi! 

I get an error:  Undefined variable $colors: /....../typo3/typo3conf/ext/mytemplate/Resources/Public/Scss/_root.scss on line 5
It is a clean TYPO3 9.5.9 installation with actual ws_scss. 
The outputfile is not written.
The SCSS is Bootstrap 4.3.1.
What I'm doing wrong?

Best regards,
Alex

**Comment by svewap** [comment]
Hi. This is no problem of this extension, because this is no bug of this extension or parts of it. 
You can get free support in forums. It's best to provide the code, otherwise they won't be able to help you.
To get paid support, you can contact https://www.wapplersystems.de.

**Comment by seitenformate** [comment]
Ok. Sorry. You are right, probably it's not a problem of ws_scss. And normally (in other installations) it works very fine. Seems to be a bug in my code or in bootstrap ... Thank you. Maybe I will try your paid support if I cannot find a solution myself :)

**Comment by bh-teufels** [comment]
sorry for reopen the issue but how is it possible to use bootstrap scss variables with ws_scss?

i included bootstrap.scss (4.6.1 - uncompiled)
after that i included my own scss file

there i want to use the bootstrap variables like

.my-headline {
 color: $yellow-600
 font-size:  $h2-font-size;
}

but get error Undefined variable
