### ISSUE TITLE
Error and unusable backend on adding custom backend styles

### ISSUE THREAD

**Issue by pprossi** [svewap/ws_scss#21]
Hi,
adding additional backend styles (Tt3V8) and clearing cache results in an error and unusable backend.

```php
if (TYPO3_MODE === 'BE') {
 	$GLOBALS['TBE_STYLES']['skins']['backend']['stylesheetDirectories'] = array_merge( $GLOBALS['TBE_STYLES']['skins']['backend']['stylesheetDirectories'],[$_EXTKEY => 'EXT:'.$_EXTKEY.'/Resources/Public/Stylesheet/Backend/'] 
);
```
![image](https://user-images.githubusercontent.com/23215844/67548742-e413aa00-f702-11e9-810f-f3919f7d23aa.png)

i think this could be solved by only append render-preProcess in frontend...

https://github.com/svewap/ws_scss/blob/9dc82ec2672dedc1e684639aa15ddc166a3c4a6b/ext_localconf.php#L6

```php
if (TYPO3_MODE === 'FE') {
	$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_pagerenderer.php']['render-preProcess']['wsscss'] = 'WapplerSystems\\WsScss\\Hooks\\RenderPreProcessorHook->renderPreProcessorProc';
}
```

**Comment by svewap** [comment]
Hi! Thank you. I will fix this with the next release!
