### ISSUE TITLE
Add typo3-ter/ws-scss to composer's replace

### ISSUE THREAD

**Issue by martinlipp** [svewap/ws_scss#22]
I'm pretty sure "typo3-ter/ws-scss" should be added to the composer.json replace section. Otherwise non-composer extensions which in turn require ws_scss (via ext_emconf.php) will always try to pull the abandoned version from the TYPO3 satis repository, even if you require svewap/ws-scss yourself in the root composer.json (which results in an install failure, because composer tries to install svewap/ws-scss and typo3-ter/ws-scss).

**Comment by svewap** [comment]
Hi! Ok, strange. I haven't had the problem yet. If you say that it has to go in there, then I will write it in.

**Comment by martinlipp** [comment]
Composer throws an error in this case since version 1.7.3. Before that it seemed to always install the typo3ter version, but that of course was also not a correct behaviour (since both typo3-ter/ws-scss and svewap/ws-scss should be placed in the typo3conf/ext/ws_scss folder, it should throw a conflict error, if both are required).

The other solution would be that the TYPO3 satis repository crawler automatically requires the Packagist version, if it is available (it already recognises abandoned packages by parsing the composer.json, so it should be doable). But I did not find the repository/bug tracker for this piece of software yet.

**Comment by svewap** [comment]
Will be fixed in next release
