### ISSUE TITLE
CSS-Crush :: data-uri()

### ISSUE THREAD

**Issue by xerc** [svewap/ws_scss#23]
https://the-echoplex.net/csscrush/#core--functions--data-uri
1. what has to be changed to get this working?
2. if it is already; what is the actual directory?

`resources/stylesheets/main.scss`
> @include "elements/scroll-top.scss"

`resources/stylesheets/elements/scroll-top.scss`
> background-image: data-uri('../../../fileadmin/pictograms/kafb-scrolltop.svg')

`fileadmin/pictograms/kafb-scrolltop.svg`
> <svg [..]

**Comment by svewap** [comment]
Is the problem still there?

**Comment by xerc** [comment]
yes; tested with version 1.1.14 and different "../" paths

**Comment by xerc** [comment]
no // why not using the Formatter\Autoprefixer as default?

**Comment by xerc** [comment]
```
main = fileadmin/main.scss
main.formatter = WapplerSystems\WsScss\Formatter\Autoprefixer
```
