### ISSUE TITLE
Bootstrap issue in scssphp / version bump

### ISSUE THREAD

**Issue by nvindice** [svewap/ws_scss#24]
Bootstrap 4.4.1 brings an awesome new feature, responsive containers. However, scssphp up to version 1.0.6 has a bug which prevents correct compilation.

This bug is fixed now in scssphp - not yet with a new release, but merged into master, see https://github.com/scssphp/scssphp/issues/69

Also, a lot of other bugs have been fixed since 0.8.2 - I would propose a version bump to the current scssphp master repo or v1.0.7 as soon as it's released.

What do you think?

**Comment by svewap** [comment]
I will upgrade as soon as possible

**Comment by nvindice** [comment]
@svewap Scssphp v1.0.7 has been released: https://github.com/scssphp/scssphp/releases

**Comment by nvindice** [comment]
Hi @svewap, any update on this? Sorry for the pressure...

**Comment by svewap** [comment]
Hi. I updated to version 1.0.8. Can you see any performance enhancements with the new cache options?

**Comment by nvindice** [comment]
@svewap The performance is incredible! I have some pretty complex SCSS files, the time needed to parse the files went down a couple of seconds! And my Bootstrap bug is finally fixed. Thank you!!

Version 1.0.9 with some more bugfixes was released a few days ago, maybe it's worth to include this minor update, too, and then release a new version?

**Comment by svewap** [comment]
Done.

**Comment by nvindice** [comment]
Wow, that was fast. Awesome. Thank you!
