### ISSUE TITLE
Interpolation in comments

### ISSUE THREAD

**Issue by haukehaller** [svewap/ws_scss#25]
Hallo,
interpolation in comments doesn't work here

scss:
/* #{$var}
->
css:
/* #{$var} */

maybe I do something wrong, I just started with this nice extension and sass.

**Comment by haukehaller** [comment]
Ah, there is a list of Sass-spec wich ScssPHP is not compliant with:
https://github.com/scssphp/scssphp/blob/master/tests/specs/sass-spec-exclude.txt

**Comment by Cerdic** [comment]
Interpolation in comments are supported
```
$var: 3;
/* #{$var} */
```

produce

/* 3 */

**Comment by stof** [comment]
what is not supported is that scssphp silently ignores failures during interpolation and uses the original comment, while dart-sass fails with an error.
