### ISSUE TITLE
TYPO3 v10 Compatibility

### ISSUE THREAD

**Issue by andreashager** [svewap/ws_scss#28]
Hey 🙂,

it would be nice if you can release your extension for TYPO3 v10.

There is already a PR for this I guess: #26 

Thanks for your efforts! 
Andi

**Comment by svewap** [comment]
Hi Andi. I will do it as soon as possible.

**Comment by svewap** [comment]
Done.

**Comment by andreashager** [comment]
Cool thanks 🥳 
I'll try it the next days 😊
