### ISSUE TITLE
no sourcemap anymore

### ISSUE THREAD

**Issue by us14v** [svewap/ws_scss#32]
ws_scss (btw, thanks for the EXT!) stopped creating sourcempas for me with 
TYPO3 9.5.19
ws_scss 1.1.16

my TS-Setup is:
````
page {

  includeCSS{    
    mainStyle = {$cssPath}/style.scss
    #mainStyle.linenumber = true
    mainStyle.sourceMap = true
    mainStyle.formatter = WapplerSystems\WsScss\Formatter\Autoprefixer
  }
}
````
this works perfectly for me with TYPO3 9.5.19 and ws_scss 1.1.13, but does nothing in 1.1.16.

if i enable linenumber, i get a sourcemap (sort of) but instead of the actual included file (say _nav.scss), i get the corresponding linenumber of the _mixins.scss file, if i use a mixin in my scss/class.

**Comment by JohannesRegner** [comment]
Have the same Problem, with TYPO3 10.4.10 and Version 1.1.18 ... -> Is the right param sourceMap = true ?

**Comment by pixelatelier** [comment]
Any news about this issue? 
I have the same problem getting no sourceMap generated.

**Comment by wolfgangww** [comment]
I have the same probs.. ;(
