### ISSUE TITLE
Error - Empty file name given

### ISSUE THREAD

**Issue by ingeniumdesign** [svewap/ws_scss#34]
After install the 1.1.16 or the 1.1.15, the Error is this: **Empty file name given**

the test with css filename dont works:

```
scssCss = fileadmin/Templates/Assets/Sass/Custom.scss
scssCss {
            outputdir = fileadmin/Templates/Assets/Css/Custom.css
            #outputdir = fileadmin/Templates/Assets/Css/
            #formatter = ScssPhp\ScssPhp\Formatter\Crunched
            formatter = ScssPhp\ScssPhp\Formatter\Expanded
            linenumber = false
}
```

with the 1.1.14 works all fine.

**Comment by machwatt** [comment]
Same problem here, downgrade to 1.1.4 works

**Comment by ingeniumdesign** [comment]
the same error with 1.1.18 and TYPO3 9.5

**Comment by svewap** [comment]
Solved in the next release
https://github.com/svewap/ws_scss/commit/89eddf01d099903740a8bc9c18fc8bd3af7fff4b

**Comment by ingeniumdesign** [comment]
Okay perfect! In the V10 and V9 dont works by the way ;)

**Comment by ingeniumdesign** [comment]
GIT Version works fine!

**Comment by machwatt** [comment]
When do you plan the next Release to TER?
