### ISSUE TITLE
Cannot resolve Windows-style directory symlinks or Windows junctions for partial path

### ISSUE THREAD

**Issue by scarcloud** [svewap/ws_scss#37]
Targeting the [`scssphp/scssphp`](https://github.com/scssphp/scssphp) sourcecode included in this repository which resolves to v1.1.1, but after checking the current release sourcecode we think the problem has persisted.

We are using `ws_scss` to compile SCSS that consists of a base located in our site package and partials from other extensions. Running on a Windows machine, the underlying `scssphp` was not able to properly resolve a path containing a Windows-style directory symlink nor a junction.

```
`../../../../../public/typo3conf/ext/other_sitepackage/Resources/Public/Stylesheets/variables` file not found for @import: C:/path/to/repository/public/typo3conf/ext/our_sitepackage/Resources/Public/Stylesheets/style.scss on line 1, at column 0

Call Stack:
#0 import C:/path/to/repository/public/typo3conf/ext/our_sitepackage/Resources/Public/Stylesheets/style.scss (unknown file) on line 1
```

We traced back the problem to `\ScssPhp\ScssPhp\Compiler::findImport`, where a full path is a string concatenation of the directory, a separator, and the full filename:
```
$full = $dir . $separator . $full;
```

Testing problem resolutions we could fix it by generating a `realpath` result for the concatenated string
```
$full = realpath($dir . $separator . $full);
```

Why exactly do you include a sourcecode version of `scssphp/scssphp` while simultaneously listing it as a dependency?

Will post a pull request in a few.

I'm also linking the [related issue at `scssphp/scssphp`](https://github.com/scssphp/scssphp/issues/176).

**Comment by svewap** [comment]
Many thanks for your cooperation. However, the problem is not related to the extension itself but to the scssphp program it contains. Issues related to it are best submitted to the original project, as you have already done.
As soon as the bug is fixed there, I can update my extension.

**Comment by YetiCGN** [comment]
@svewap Thanks for the quick reply. Can you provide an answer to this question?

> Why exactly do you include a sourcecode version of scssphp/scssphp while simultaneously listing it as a dependency?

**Comment by svewap** [comment]
@YetiCGN Sure. In TYPO3 you can integrate extensions in two different ways. The traditional one via Extension Manager or via composer. With the Extension Manager, there is no possibility of automatically embedding the non-extension code. The extension must bring it with it. With composer this is easier.
