### ISSUE TITLE
Editing imported scss-files do not trigger recompiling

### ISSUE THREAD

**Issue by jyskweb** [svewap/ws_scss#5]
This issue regards v1.1.6. Version 1.1.4 did the job well... and still does in TYPO3 8.7.
Changes of an imported file (@import) do not have any effect until the file containing the @import-instruction is updated.

**Comment by svewap** [comment]
Sorry, but I cannot confirm this problem. I always working with a bootstrap SASS file structure with just one main file containing imports. I always working in imported files and the recompiling is always triggered.

**Comment by jyskweb** [comment]
I found a typo in my file.

This is _not_ working:
`@import 'file';`

This _is_ working:
`@import "file";`

Sorry for the inconvenience!

**Comment by jyskweb** [comment]
There is a little twist...
If I import files by typoscript variables, the changes in those files do not trigger a recompiling as they did in version **1.4**.   

_Example:_
In setup (file #1):
```
plugin.tx_wsscss.variables.addstyles := addToList("../../../{$plugin.tx_news.settings.cssFile}")
```
In setup (file #2):
```
plugin.tx_wsscss.variables.addstyles := addToList("../../../path/dropdownmenu")
```
In scss:   
```
@import $addstyles;
```

This still works in **1.6** but changes in imported files are not recognized by the extension. Maybe it would be more appropriated to make a typoscript setting for dynamic import of scss-files?

**Comment by jyskweb** [comment]
This will solve my issue in v1.1.11.
RenderPreProcessorHook.php in line 154:

`if ($cache->has($cacheKey) && !$setup['plugin.']['tx_wsscss.']['noCache']) {`

**Comment by svewap** [comment]
I'll take a look at this.

**Comment by svewap** [comment]
Unfortunately I cannot reproduce the problem. I myself use the bootstrap template, which consists of many files, and this works fine if I change files.
So far no one else has confirmed the problem.
