### ISSUE TITLE
Class 'ScssPhp\ScssPhp\OutputStyle' not found

### ISSUE THREAD

**Issue by marcelmarty** [svewap/ws_scss#53]
Issue occurs on each on my TYPO3 11.5.x installations when installing ws_scss and deleting the cache.

**Comment by svewap** [comment]
Can you please post the complete stack trace?

**Comment by svewap** [comment]
Can you please test the current master version? https://github.com/svewap/ws_scss/archive/refs/heads/master.zip

**Comment by marcelmarty** [comment]
Unfortunately, I have still the same error. :-/

**Comment by p-view** [comment]
have the same problem in Typo3 13

**Comment by wtdesign** [comment]
I have the same problem in TYPO3 v13. We don't use composer.

**Comment by mitausblick** [comment]
Same here in TYPO3 13.

**Comment by marcelmarty** [comment]
Can confirm that.. Same error in TYPO3 v13.4.5 - ws_scss 13.0.1

**Comment by wtdesign** [comment]
we wrote this in our extension **ext_localconf.php**. This works for us 


```
/***************
 * ws_scss
 */
if (!class_exists(\ScssPhp\ScssPhp\Version::class, true)) {
    $extPath = ExtensionManagementUtility::extPath('custom_extension');
    require_once $extPath . 'Resources/Private/Vendor/scssphp/scss.inc.php';
}

```

and pasted then the file **scss.inc.php** int this path "EXT:custom_extension/Resources/Private/Vendor/scssphp/scss.inc.php". Note the php version.


```
<?php

if (version_compare(PHP_VERSION, '5.6') < 0) {
    throw new \Exception('scssphp requires PHP 5.6 or above');
}

if (! class_exists('ScssPhp\ScssPhp\Version')) {
    spl_autoload_register(function ($class) {
        if (0 !== strpos($class, 'ScssPhp\ScssPhp\\')) {
            // Not a ScssPhp class
            return;
        }

        $subClass = substr($class, strlen('ScssPhp\ScssPhp\\'));
        $path = __DIR__ . '/src/' . str_replace('\\', '/', $subClass) . '.php';

        if (file_exists($path)) {
            require $path;
        }
    });
}
```

in the **scssphp** folder you also have to insert the "**src**"-folder with all folders and files
