### ISSUE TITLE
 PHP Warning: Undefined array key "outputStyle" 

### ISSUE THREAD

**Issue by fischhase** [svewap/ws_scss#55]
Hallo Sven,
thanks for your great work. I often use your sass extension.

at my present project I have some problem. I use TYPO3 11.5 with PHP 8. I imported my usual setup from previous TYPO3 10. Now your Extension gives an Error:

`PHP Warning: Undefined array key "outputStyle"`
The outputStyle has a standard setting, but even when I specify it, the Error accures. If I switch back to PHP 7 the error is gone and XDebug wants more nested levels. I deactivated XDebug and after some seconds I get the message:
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 81920 bytes) in /usr/www/users/hldfdhg/webseite/freunde-der-herrenhaeuser-gaerten.com/typo3conf/ext/ws_scss/Resources/Private/scssphp/src/Compiler.php on line 4934`
I switched back to PHP 8 an set the Array $subConf['outputStyle'] = 'expanded'; in line 133 of RenderPreProcessorHook.php, just before usage. In this case, the exhausted memories appears immediately.

Is there a bug in the TYPO3 11/PHP8 update or is it my fault?

Thanks for help.

**Comment by fischhase** [comment]
Hallo Sven,
there was a bug in the TER version, but in this version it is ok. The exhausted memory issue was a problem in my mixins. There was a loop implemented. The debug messages only appear if in the htaccess  "SetEnv TYPO3_CONTEXT Development" is written. 
So I selfclose this issue.
Thanks anyway

**Comment by bh-teufels** [comment]
i get the same Error
Core: Error handler (FE): PHP Warning: Undefined array key "outputStyle" in /typo3conf/ext/ws_scss/Classes/Hooks/RenderPreProcessorHook.php line 132

Typo3 11.5.14
PHP 8.1
ws_scss 1.2.1

if i set 
outputStyle = compressed 
inside my includeCSS 
the error does not apear
