### ISSUE TITLE
outputdir ignored ?

### ISSUE THREAD

**Issue by HorstBaumann** [svewap/ws_scss#66]
by switching from 1.2.1 to 11.0.*
it seems that the outputdir value (set in typoscript) is no longer working

page.includeCSS {
        scss = {$templatePath}/Private/SCSS/loader.scss
        **scss.outputdir = {$templatePath}/Public/css/**
        scss.disableCompression = 1
        scss.excludeFromConcatenation = 1
}

TYPO3 11.5.21
ws_scss 11.0.2
PHP 8.0

I fixed it temporarily by quick and dirty changing line 75 in Classes/Compiler.php:
$outputDir = 'mytemplatepath/css/';

**Comment by typo3-solution** [comment]
Hey Horst, 
just use:
scss.outputfile 

see also:  https://docs.typo3.org/p/wapplersystems/ws-scss/12.0/en-us/Usage/Index.html

Liebe Grüße, Simon

**Comment by HorstBaumann** [comment]
perfect  -thanks !
