### ISSUE TITLE
Conflict with same Scss fileName in v11 branch

### ISSUE THREAD

**Issue by nhovratov** [svewap/ws_scss#77]
I have a multi-domain setup, where each site has a Main.scss file. Due to the missing hash of the file path, a Css file of the wrong site is loaded.

In the old version 1.2.1 this was added to the hash:
`hash('sha1', $file)` which seems to be missing now.

Might also affect the current v12 branch.

For reference: https://github.com/WapplerSystems/ws_scss/blob/80b763f7b1962bf26dcc38de8ba2f48c1e89e501/Classes/Hooks/RenderPreProcessorHook.php#L160-L165

**Comment by svewap** [comment]
You can use the <scssfile>.outputfile parameter as workaround.
