### ISSUE TITLE
1.1.9 breaks in 8.7.20

### ISSUE THREAD

**Issue by pquerner** [svewap/ws_scss#8]
I've updated from 1.1.8 to 1.1.9 in a TYPO3 installation (8.7.20) and it breaks css generation.

1.1.8 output:
```
<link rel="stylesheet" type="text/css" href="/typo3temp/ws_scss/main_a95890ebb669ac659bdf758a4a0bdcfe84601c87.css?1542118606" media="all">
```

1.1.9 output
```
<link rel="stylesheet" type="text/css" href="/.css18606" media="all">
```

Also the content-type is reported as ```Content-Type: application/octet-stream```, instead of ```content-type: text/css; charset=utf-8```

I've reverted back to 1.1.8 and it works. I did clear the cache multiple times via Installtool and hardremove contents of typo3temp.

**Comment by svewap** [comment]
Thank you. Is fixed in version 1.1.10.
