### ISSUE TITLE
files are not copied to temp folder

### ISSUE THREAD

**Issue by matin73** [svewap/ws_scss#84]
I have upgraded to version 11.03. in typo3 11 an now the background-images are not copied to folder temp:
background: transparent url('../../../typo3temp/assets/svg/function/link-arrow-blue.svg') no-repeat center right
in old version css looked like and worked:
background: transparent url('../../../typo3conf/ext/xxx/Resources/Public/svg/function/link-arrow-blue.svg') no-repeat center right;

**Comment by svewap** [comment]
The ws_scss extension has never copied image files and never will. The paths must therefore be adapted so that they are still correct after the compilation process. The easiest way is to use absolute paths up to and including TYPO3 11. Example:
“/typo3conf/ext/xyz/Resources/Public/Images/image.png”
